name: Update Odoo Dockerfiles

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 2'  # Run at 00:00 UTC every Tuesday
  push:
    branches:
      - master
    paths:
      - 'update_dockerfiles.py'
      - 'data.json'
      - '.github/workflows/update_repository.yml'

# Add permissions for the GitHub token
permissions:
  contents: write

jobs:
  update-dockerfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update Dockerfiles
        run: |
          python update_dockerfiles.py

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add */Dockerfile
          git commit -m "Update Dockerfiles" || echo "No changes to commit"
          git push origin ${GITHUB_REF##*/}